[package]
name = "integration_tests"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
gdext_coroutines = { path = "..", features = ["async"] }
godot = { package = "godot", git = "https://github.com/godot-rust/gdext" }
smol = "2.0"
async-compat = "0.2.4"